# 컬럼명 한글명으로 변환
### 샘플 trfcard(0)폴더에 있는 파일을 기준으로 우선변환

In [1]:
import pandas as pd

In [3]:
sample = pd.read_csv("./01_data_원본/포항시_버스_사용자_교통카드_사용_내역/trfcard (0)/trfcard.csv")

In [7]:
#컬럼 정의서 가져오기
sample_m = pd.read_excel("./01_data_원본/포항시_버스_사용자_교통카드_사용_내역/trfcard (0)/trfcard_columns.xlsx",
                              sheet_name = "컬럼 정의서"
                              , usecols ="B, C"
                              , header = 2)

In [8]:
sample_m

       컬럼명 (영문)     컬럼명 (한글)
0       on_date         승차시각
1      off_date         하차시각
2    route_name          노선명
3         descr         노선설명
4      age_type         승객연령
5      trans_yn         환승여부
6     addfee_yn       추가운임여부
7   start_bstop        승차정류장
8   start_gps_x  승차정류장 GPS X
9   start_gps_y  승차정류장 GPS Y
10    end_bstop        하차정류장
11    end_gps_x  하차정류장 GPS X
12    end_gps_y  하차정류장 GPS Y

In [15]:
#한글명으로 칼럼명 변경

#데이터 값들을 딕셔너리로 변경
sample_list= sample_m.to_dict("records")

#깨끗한 삽입용 데이터 베이스 생성
new_dict = {}

#ㄹfor 문
for dict_kv in sample_list :
    new_dict[dict_kv["컬럼명 (영문)"]] = dict_kv["컬럼명 (한글)"]

new_dict

sample_kor = sample.rename(columns =  new_dict)
sample_kor

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200327051412,20200327051714,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675
1,20200327051514,20200327054956,175,문덕-고속터미널-선린병원-달전,일반,N,N,준양주택3차,129.403063,35.960871,오거리,129.366312,36.031816
2,20200327052343,20200327054659,200,양덕-남구청(야구장)-구룡포,일반,N,N,두호동주민센터,129.378910,36.060370,남구보건소,129.396855,35.992624
3,20200327052449,20200327055412,100,문덕-흥해-신광,일반,N,N,천마아파트,129.409928,35.949403,홈플러스,129.364640,36.030950
4,20200327052848,20200327055231,175,문덕-고속터미널-선린병원-달전,일반,N,N,오천농협세계지점,129.415970,35.967450,죽도시장,129.365169,36.035704
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4978,20200327232513,20200327232800,101,양덕-고속터미널-동해,일반,Y,N,포은중앙도서관,129.367873,36.043187,롯데아파트,129.377403,36.056943
4979,20200327232740,20200327233319,107,문덕-시외(고속)터미널-흥해,일반,N,N,KTX포항역(시내행),129.342368,36.072374,우현경로당,129.362232,36.049878
4980,20200327232829,20200327233446,500,문덕-시외터미널-흥해-청하-월포,일반,N,N,시외버스터미널,129.350290,36.013280,연일파출소,129.345750,35.997470
4981,20200327233328,20200327233442,107,문덕-시외(고속)터미널-흥해,일반,N,N,우현경로당,129.362232,36.049878,도심환승센터,129.365165,36.043435
4982,20200327233622,20200327234014,105,양덕-시외터미널-지곡,일반,N,N,포은중앙도서관,129.367873,36.043187,두호남부초등학교,129.373390,36.060530

In [17]:
new_dict

{'on_date': '승차시각',
 'off_date': '하차시각',
 'route_name': '노선명',
 'descr': '노선설명',
 'age_type': '승객연령',
 'trans_yn': '환승여부',
 'addfee_yn': '추가운임여부',
 'start_bstop': '승차정류장',
 'start_gps_x': '승차정류장 GPS X',
 'start_gps_y': '승차정류장 GPS Y',
 'end_bstop': '하차정류장',
 'end_gps_x': '하차정류장 GPS X',
 'end_gps_y': '하차정류장 GPS Y'}

In [68]:
numLIst=range(1,100)
df=pd.DataFrame()

for i in range(1,100) :
    data = pd.read_csv("./01_data_원본/포항시_버스_사용자_교통카드_사용_내역/trfcard ({})/trfcard.csv".format(i))

NameError: name 'df_' is not defined

In [48]:
numLIst=range(0,100)
numLIst

range(0, 100)